apiVersion: v1
kind: Service
metadata:
  name: accounts-be-svc
  labels:
    app: accounts-be-svc
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: accounts-be-proxy
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-be
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: accounts-be
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-be-configmap
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      # limit_req_zone $binary_remote_addr zone=one:10m rate=30r/m;

      server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        location / {
            proxy_pass             http://accounts-be:8080;
            proxy_set_header       Host $host;
            add_header             X-Host      $hostname;
            # limit_req zone=one;         
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-be-proxy
  labels:
    app: accounts-be-proxy
spec:
  selector:
    matchLabels:
      app: accounts-be-proxy
  template:
    metadata:
      labels:
        app: accounts-be-proxy
    spec:
      containers:
        - image: nginx:1.17-alpine
          name: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: accounts-be-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-be
  labels:
    app: accounts-be
spec:
  selector:
    matchLabels:
      app: accounts-be
  template:
    metadata:
      labels:
        app: accounts-be
    spec:
      containers:
        - image: accounts-be:1.0
          name: accounts-be
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
