CREATE DATABASE orders;

\c orders; # Re-enter password

CREATE TABLE PRODUCT (
    ID SERIAL PRIMARY KEY, 
    PRODUCT_NUMBER VARCHAR(50),
    DESCRIPTION VARCHAR(100), 
    UNIT_COST FLOAT
);

CREATE TABLE ORDER_DETAIL (
    ID SERIAL PRIMARY KEY,
    ORDER_NUMBER VARCHAR(15),
    PRODUCT_ID INT REFERENCES PRODUCT(ID),
    QUANTITY INT,
    TOTAL FLOAT
);
